### ISSUE TITLE
Storage account prefix should be 'st' instead of 'sa'

### ISSUE THREAD

**Issue by cndaan** [CloudNationHQ/az-cn-module-tf-sa#28]
Storage account prefix should be 'st' instead of 'sa'

https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations#storage

**Comment by dkooll** [comment]
solved by https://github.com/CloudNationHQ/az-cn-module-tf-sa/pull/30
